name: Deploy .NET 8 to Azure

on:
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Define App Name
        run: |
          if [ "${GITHUB_REF_NAME}" == "develop" ]; then
            echo "APP_NAME=minhaapi-dev" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "homolog" ]; then
            echo "APP_NAME=minhaapi-hml" >> $GITHUB_ENV
          else
            echo "APP_NAME=minhaapi-prod" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: ./publish